language: node_js
sudo: required
services:
- docker
node_js:
- '8'
before_install:
- "./scripts/setup-db.sh"
after_success: yarn run coverage
deploy:
  provider: npm
  email: nick@cuthbert.co.za
  api_key:
    secure: cOuA0H6c6MJD3RaEgXYlDfVu1vpYlFD6KiAS9mreRsKhkjLy2V5pJmDwPGOcf4epVhCILwib3HOXKa3iCU7lHodNwBKzOOlL65EbA71PnUxsLkZ3fVarTziY1Kzllof0+DVLFGNjqkNelBsLii+29I8qcKGFvtTb+7HuI0a2m8BwuqKgee4TvBjKZEWs/IRJ8F4cbPzkuDz4gjKJawRRd2yH0nQfXRRTtGlnvw7ugS07iKME1+13w8BgUQ0a1RqPjQAqbuPFmpsnDGRKSDS19pgbXP3UzZh6P7E3XytVI32fu0o5nWvJOcmCwaqna8VEqQgk7GJsC98hbDAJ9bhmSId6u1n3BFMyEknPiY5MlDaOsJRFGDzj4jRByrBht+cX0yo7Qf+5nNOszVZFvuNyEkGfAunbN1ZvXkJ7BvOEHUyNrBrmRT/fHyEhH/ESAVbmJN1yFaXY5/8jeA07trx4Pw+cgBKXL+YkdVBgrnm3T/qMXO3rGS3l58jwQQjUmgu5ypux/IOS8rBWv9PCxJVzsJ0opmpcTe76HsyTivpDX7vWc3JmDda/qPQeHN1mqA6Bo4qmv129ZXDRAN93gxU7MYlCKW8Wtga/vwBE1CAvVgl+um7AUvCUSPhD0Kko2WGafzPJQL+RzeVzQgqsg5Om4zqDvM2Y340V6q9BxZnEZoA=
  on:
    tags: true
    branch: master
    repo: ncthbrt/nact-persistence-postgres
notifications:
  slack:
    secure: uLOgivlomUhPxRBNEdqnLcFNCag+4xY1ibliDUvH3/h2+MEg2G+sd6FMd1QEpEIUEdzMV+Yhqoxrf9Goeq2hjKi5UbEB3ky9n8Yql6kRTmPeXfvVAMSU1UsQhGDX6IUyENpsywkm0A2QuMP/+3Z7EIXd9cQ4G6iLd3CT+aIXMCz7LY11WaLiwy1zYDoXDA0d6uYgUrUQB3k0TdUQlCC5DqoWJxCAYOawzrKZnrlfrX5VF2P4asLBAWWfEhuawhFVdRoWbE7T58Uw4YB51kG9p6ngtxMM5vLqqoOT+ARQIH/10+Tb/X7D596AuXZt6bBM4LSqaPTXMMlQk7AUTws3dg25wiJbfdPniMzJ8do+6xjf9vz2IE+PYLRU8xraOh5ZG8V2dK4QULpwww2Dbq7DE99kRrAqSMzrkZaklfILRvGSOsAgVrJsYdzuU5DGXGK28QpfGS/8ibcIuo253z+08GEmpgFFaHCH2eG7UiyOkdxjoGPDlkq7fjodhCx0TyS3VnWMrEJNw6+LU47LyFNuQZO9ra7rZdquISJHEnoR092zdS7M/niKvkxCLa22Lrbu4x5vRXW/WV8v28xnqNeFP4Bul6cyo0CefGYpy3LabvHJsJ6Ku6om0skDF7bOGptFvtEH3lWn4A06vqkE5n6UEQ51mHb5ms7ijwUpjd29bc0=
    on_success: change
    on_failure: always
